### ISSUE TITLE
private 'de.sandec' API? FLOSS license?

### ISSUE THREAD

**Issue by RalphSteinhagen** [Sandec/JMemoryBuddy#1]
First, thanks for sharing your code and experience and allow me to be the first commenter.

For a smaller scope, the examples work fine. I am still wrapping my head around how this could be used (efficiently) within a (much) larger (also UI-related) context. 

What is the intended license? There appears to be a bit of ambiguity. Will it be FLOSS?

Some of the (static) methods and interfaces (e.g. 'static interface MemTestHelper') do not have a specific scope outside 'de.sandec' domain defined which causes compile-time errors such as:
`The type JMemoryBuddy.MemTestHelper from the descriptor computed for the target context is not visible here.` Maybe make them explicitly public and/or refactor them into separate files?

I understand why the library throws an [unchecked `RuntimeException`](https://docs.oracle.com/javase/tutorial/essential/exceptions/runtime.html). At the same time, what about throwing a more specific one instead, e.g. one derived from 'AssertionError' as it is done within the Junit frame-work?

Since you mentioned that this is used elsewhere as well, do you have some real-world examples in a public repository?

Thanks again!

**Comment by FlorianKirmaier** [comment]
I missed to update the README after the last update. The issue with the private API should be fixed with the version 0.1.1.
I've added the Apache 2.0 License. I think it's the most commonly used "to with it whatever you want" license.

When the library wouldn't properly in some situation, for example because of a very large heap or a differenct JVM or GC implementation, then it should be easy to verify, it's not working properly. The heapdump wont show a GC root. The Library also warn you, when tests are unexpected slow.
It's also planned to make it more configurable on how it's testing.

Thank you for the suggestion regarding Exception. Im Changing it now to AssertionError, as it's done in JUnit.

For a sample, take a look at my Pullrequest which fixes some memoryleaks in controlsfx: https://github.com/controlsfx/controlsfx/pull/1202/files
Im also using it on various my private projects, especially [JPro](https://www.jpro.one/)
